batch_size: 256  #original 128
epochs: 80  #original 80
lr: 0.001

device: cuda:0
num_workers: 4  #original 4
seed: 1234
use_wandb: False
weight_decay: 0.0001  # 新規追加

data_dir: data

# Evaluation
model_path: 